// Auto-generated by `pnpm --filter @tm/mobile i18n:generate` from the English
// catalog (locales/en.json) via i18next-resources-for-ts. Do not edit by hand;
// `i18n:check` fails CI when this file is stale.
import "i18next";

import type Resources from "./resources";

declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: "translation";
    // Catalogs are flat JSON with dot-notation keys; keys are matched literally.
    keySeparator: false;
    nsSeparator: false;
    resources: Resources;
  }
}
