/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        "primary-emphasis": "rgb(var(--color-primary-emphasis) / <alpha-value>)",
        background: "rgb(var(--color-background) / <alpha-value>)",
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        "chat-bg": "rgb(var(--color-chat-bg) / <alpha-value>)",
        incoming: "rgb(var(--color-incoming) / <alpha-value>)",
        outgoing: "rgb(var(--color-outgoing) / <alpha-value>)",
        "on-background": "rgb(var(--color-on-background) / <alpha-value>)",
        "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        muted: "rgb(var(--color-muted) / <alpha-value>)",
        border: "rgb(var(--color-border) / <alpha-value>)",
        status: "rgb(var(--color-status) / <alpha-value>)",
        danger: "rgb(var(--color-danger) / <alpha-value>)",
        warning: "rgb(var(--color-warning) / <alpha-value>)",
      },
      spacing: {
        "2xs": "2px",
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "32px",
        "4xl": "48px",
      },
      fontSize: {
        "2xs": ["10px", { lineHeight: "12px" }],
        xs: ["12px", { lineHeight: "14px" }],
        sm: ["14px", { lineHeight: "18px" }],
        base: ["16px", { lineHeight: "20px" }],
        lg: ["18px", { lineHeight: "22px" }],
        xl: ["20px", { lineHeight: "24px" }],
        "2xl": ["24px", { lineHeight: "28px" }],
        "3xl": ["30px", { lineHeight: "34px" }],
      },
      borderRadius: {
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "24px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
